### ISSUE TITLE
Incorrect 'Equal' function

### ISSUE THREAD

**Issue by RasoulAM** [willscott/go-selfish-bitswap-client#6]
https://github.com/willscott/go-selfish-bitswap-client/blob/16e59abbd25751d2a146adb502fddc59762ccee0/message/cid.go#L43

Should this be `return c.Cid.Equals(c.Cid)`?

**Comment by willscott** [comment]
thanks for catching that!

that said - i think this is really just used as a helper for serialization/deserialization - i don't think the method was actually used

**Comment by RasoulAM** [comment]
Yup, I haven't seen it used anywhere yet. But thought to point it out in case it was used in the future:)
